# Generated by Django 2.0 on 2018-09-14 16:08

import base.apputil
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locus', '0001_initial'),
        ('business', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('image', models.FileField(upload_to=base.apputil.App_UserFilesDir)),
                ('price', models.IntegerField(default=100)),
                ('discount', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=100)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2018, 9, 19, 16, 8, 55, 775873, tzinfo=utc))),
                ('fk_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='OfferAddressMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locus.Address')),
                ('fk_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferCategoryMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
                ('fk_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
