# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=30)),
                ('business_desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'business',
                'verbose_name': 'business',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'verbose_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(blank=True, max_length=50)),
                ('location_pin', models.CharField(blank=True, max_length=10)),
                ('fk_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.City')),
                ('fk_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Country')),
            ],
            options={
                'verbose_name_plural': 'locations',
                'verbose_name': 'location',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=30)),
                ('image_name', models.CharField(max_length=50)),
                ('discount', models.CharField(blank=True, max_length=3)),
                ('start_date', models.DateTimeField(blank=True)),
                ('expire_date', models.DateTimeField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Location')),
            ],
            options={
                'verbose_name_plural': 'offers',
                'verbose_name': 'offer',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('fk_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Country')),
            ],
            options={
                'verbose_name_plural': 'states',
                'verbose_name': 'state',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.State'),
        ),
    ]
