# Generated by Django 2.0 on 2017-12-06 17:42

import common.apputil
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('user', '0001_initial'),
        ('locus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('image', models.FileField(upload_to=common.apputil.App_UserFilesDir)),
                ('price', models.IntegerField(default=100)),
                ('discount', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField(default=datetime.datetime(2017, 12, 11, 17, 42, 15, 948822, tzinfo=utc))),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='OfferCategoryMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
                ('fk_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferLocationMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locus.Address')),
                ('fk_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
        ),
    ]
