# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 7, 17, 55, 4, 615637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
