# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 19, 39, 42, 720724, tzinfo=utc)),
        ),
    ]
