# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20170423_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 18, 41, 1, 829028, tzinfo=utc)),
        ),
    ]
