# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20170423_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 11, 4, 8, 143613, tzinfo=utc)),
        ),
    ]
