# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-12 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20170521_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'business',
                'verbose_name': 'business',
            },
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='start_date',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 6, 36, 58, 182466, tzinfo=utc)),
        ),
    ]
