# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=upload.models.user_files_dir)),
                ('used', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
