gStates = {'India': [{'name': 'Andhra Pradesh',
				'cities':['Hyderabad'],
				},
				{'name': 'Chandigarh',
				'cities':['Chandigarh'],
				},
				{'name': 'Delhi',
				'cities':['New Delhi', 'Central Delhi', 'East Delhi', 'North East Delhi', 'North West Delhi', 'South Delhi'],
				},
				{'name': 'Himachal Pradesh',
				'cities':['Shimla', 'Hamirpur(HP)'],
				},
				{'name': 'Karnataka',
				'cities': ['Bangalore'],
				},
				{'name': 'Maharashtra',
				'cities': ['Mumbai', 'Pune'],
				},
				{'name': 'Tamil Nadu',
				'cities': ['Chennai', 'Coimbatore'],
				},
			],
        'USA':[{'name': 'California',
			'cities': ['San Francisco', 'Los Angeles'],
			},
            {'name': 'New York',
			'cities': ['New York', 'Buffalo'],
			},
			{'name': 'Florida',
			'cities': ['Alachua'],
			},
		],
	}
