gCountries = {'India': [{'name': 'Andhra Pradesh',
				'cities':['Hyderabad'],
				},
				{'name': 'Chandigarh',
				'cities':['Chandigarh'],
				},
				{'name': 'Delhi',
				'cities':['New Delhi', 'Central Delhi', 'East Delhi', 'North East Delhi', 'North West Delhi', 'South Delhi'],
				},
				{'name': 'Himachal Pradesh',
				'cities':['Shimla', 'Hamirpur(HP)'],
				},
				{'name': 'Karnataka',
				'cities': ['Bangalore'],
				},
				{'name': 'Maharashtra',
				'cities': ['Mumbai', 'Pune'],
				},
				{'name': 'Tamil Nadu',
				'cities': ['Chennai', 'Coimbatore'],
				},
			],
        'USA':[{'name': 'California',
			'cities': ['San Francisco', 'Los Angeles'],
			},
            {'name': 'New York',
			'cities': ['New York', 'Buffalo'],
			},
			{'name': 'Florida',
			'cities': ['Alachua'],
			},
		],
	}


gCategories = [
	{'name':'All', 'desc': '*',
		'sub': [
			{'name':'Computers & Electronics', 'desc':'Computers, Laptops, tablets, Phones, Desktops, Computer Accessories',
				'sub': [
					{'name':'Laptops', 'desc':'Laptop computers'},
					{'name':'Desktops', 'desc':'Desktop computers'},
					{'name':'Mobile Phones', 'desc':'Smart phones, feature phones'},
					{'name':'Tablets', 'desc':'Tablet computers'},
					{'name':'Smart TV', 'desc':'TV, Smart TV'},
					{'name':'Camera', 'desc': 'Cameras'},
					{'name':'Electronic Accessories', 'desc':'Accessories',
						'sub': [
							{'name':'Mobile Cases', 'desc':''},
							{'name':'Headphones & Headsets', 'desc':''},
							{'name':'Power Banks', 'desc':''},
							{'name':'Screenguards', 'desc':''},
							{'name':'Memory Cards', 'desc':''},
							{'name':'Smart Headphones', 'desc':''},
							{'name':'Mobile Cables', 'desc':''},
							{'name':'Chargers', 'desc':''},
							{'name':'Selfie Sticks', 'desc':''},
						],
					},
				],
			},
			{'name':'Appliances', 'desc': 'Home, Kitchen Appliances',
				'sub': [
					{'name':'Televisions', 'desc':'Televisions'},
					{'name':'Refrigerators', 'desc':'Refrigerators'},
					{'name':'Air Conditioners', 'desc':'Air Conditioners'},
					{'name':'Geysers', 'desc':'Geysers'},
					{'name':'Washing Machines', 'desc':'Washing machines'},
					{'name':'Kitchen Appliances', 'desc':'Kitchen Appliances',
						'sub':[
							{'name':'Mixer/Juicer/Grinder', 'desc':''},
							{'name':'Food Processors', 'desc':''},
							{'name':'Induction Cooktops', 'desc':''},
							{'name':'Sandwich Makers', 'desc':''},
							{'name':'Popup Toasters', 'desc':''},
							{'name':'Hand Blender', 'desc':''},
							{'name':'Electric Kettle', 'desc':''},
							{'name':'Oven Toaster Grills', 'desc':''},
							{'name':'Coffee Makers', 'desc':''},
							{'name':'Electric Cookers', 'desc':''},
							{'name':'Dishwashers', 'desc':''},
							{'name':'Chimneys', 'desc':''},
							{'name':'Microwave Ovens', 'desc':''},
							{'name':'Water Purifiers', 'desc':''},
						],
					},
					{'name':'Home Appliances', 'desc':'Home Appliances',
						'sub': [
							{'name':'Irons', 'desc':'',},
							{'name':'Air Purifiers', 'desc':'',},
							{'name':'Water Purifiers', 'desc':'',},
							{'name':'Vacuum Cleaners', 'desc':'',},
							{'name':'Smart Home Automation', 'desc':'',},
						],
					},
				],
			},
			{'name':'Fashion & Clothing Men', 'desc':'boys, men',
				'sub': [
					{'name': 'Clothing', 'desc':'boys, men',
						'sub':[
							{'name':'Top wear', 'desc':'',
								'sub':[
									{'name':'T-Shirts', 'desc':'boys, men',},
									{'name':'Shirts', 'desc':'boys, men',},
									{'name':'Kurtas', 'desc':'boys, men',},
									{'name':'Suits & Blazers', 'desc':'boys, men',},
									{'name':'Jackets', 'desc':'boys, men',},
									{'name':'Sweatshirts', 'desc':'boys, men',},
								],
							},
							{'name':'Bottom wear', 'desc':'boys, men',
								'sub':[
									{'name':'Jeans', 'desc':'boys, men',},
									{'name':'Shorts', 'desc':'boys, men',},
									{'name':'Cargos', 'desc':'boys, men',},
									{'name':'Track pants', 'desc':'boys, men',},
								]
							},
							{'name':'Sports wear', 'desc':'boys, men',
								'sub':[
									{'name':'Sports T-Shirts', 'desc':'boys, men',},
									{'name':'Track Pants', 'desc':'boys, men',},
									{'name':'Track Suits', 'desc':'boys, men',},
									{'name':'Shorts', 'desc':'boys, men',},
								]
							},
							{'name':'Innerwear & Sleepwear', 'desc':'boys, men',
								'sub':[
									{'name':'Briefs & Trunks', 'desc':'boys, men',},
									{'name':'Vests', 'desc':'boys, men',},
									{'name':'Boxers', 'desc':'boys, men',},
									{'name':'Thermals', 'desc':'boys, men',},
									{'name':'Ties, Socks, Caps', 'desc':'boys, men',},
									{'name':'Kurta, Pyjama', 'desc':'boys, men',},
								]
							},
						],
					},
					{'name':'Footwear', 'desc':'boys, men',
						'sub':[
							{'name':'Sports Shoes', 'desc':'boys, men',},
							{'name':'Casual Shoes', 'desc':'boys, men',},
							{'name':'Formal Shoes', 'desc':'men',},
							{'name':'Sandals & Floaters', 'desc':'boys,men',},
							{'name':'Flip Flops', 'desc':'boys,men',},
							{'name':'Loafers', 'desc':'boys, men',},
							{'name':'Boots', 'desc':'boys, men',},
							{'name':'Running Shoes', 'desc':'boys, men',},
							{'name':'Sneakers', 'desc':'boys, men',},
						],
					},
					{'name':'Accessories', 'desc':'boys, men',
						'sub':[
							{'name':'Backpacks', 'desc':'boys, men',},
							{'name':'Wallets', 'desc':'boys, men',},
							{'name':'Belts', 'desc':'boys, men',},
							{'name':'Sunglasses', 'desc':'boys, men',},
							{'name':'Luggage & Travel', 'desc':'boys, men',},
							{'name':'Jewellery', 'desc':'boys, men',},
							{'name':'Sports & Fitness Store', 'desc':'boys, men',},
							{'name':'Smart Watches', 'desc':'boys, men',},
							{'name':'Smart Bands', 'desc':'boys, men',},
							{'name':'Smart Watches', 'desc':'boys, men',},
							{'name':'Trimmers', 'desc':'boys, men',},
							{'name':'Shavers', 'desc':'boys, men',},
							{'name':'Perfumes', 'desc':'boys, men',},
							{'name':'Deodrents', 'desc':'boys, men',},
						],
					},
				]
			},
			{'name':'Fashion & Clothing Women', 'desc':'girls, women',
				'sub': [
					{'name':'Indian & Fusion Wear', 'desc':'girls, women',
						'sub':[
							{'name':'Kurtas & Suits', 'desc':'girls, women',},
							{'name':'Kurtis, Tunics & Tops', 'desc':'girls, women',},
							{'name':'Leggings, Salwars, Churidars', 'desc':'girls, women',},
							{'name':'Skirts & Palazzos', 'desc':'girls, women',},
							{'name':'Sarees & Blouses', 'desc':'girls, women',},
							{'name':'Dress Material', 'desc':'girls, women',},
							{'name':'Lehenga Choli', 'desc':'girls, women',},
							{'name':'Dupattas & Shawls', 'desc':'girls, women',},
							{'name':'Jackets & Waistcoats', 'desc':'girls, women',},
						],
					},
					{'name':'Western Wear', 'desc':'girls, women',
						'sub':[
							{'name':'Dresses & Jumpsuits', 'desc':'girls, women',},
							{'name':'Tops, T-Shirts & Shirts', 'desc':'girls, women',},
							{'name':'Jeans & Jeggings', 'desc':'girls, women',},
							{'name':'Trousers & Capris', 'desc':'girls, women',},
							{'name':'Shorts & Skirts', 'desc':'girls, women',},
							{'name':'Shrugs', 'desc':'girls, women',},
							{'name':'Sweaters & Sweatshirts', 'desc':'girls, women',},
							{'name':'Jackets & Waistcoats', 'desc':'girls, women',},
							{'name':'Coats & Blazers', 'desc':'girls, women',},
						],
					},
					{'name':'Lingerie & Sleepwear', 'desc':'girls, women',
						'sub':[
							{'name':'Bras & Lingerie Sets', 'desc':'girls, women',},
							{'name':'Briefs', 'desc':'girls, women',},
							{'name':'Shapewear', 'desc':'girls, women',},
							{'name':'Sleepwear & Loungewear', 'desc':'girls, women',},
							{'name':'Swimwear', 'desc':'girls, women',},
							{'name':'Camisoles & Thermals', 'desc':'girls, women',},
						],
					},
					{'name':'Footwear', 'desc':'girls, women',
						'sub':[
							{'name':'Flats & Casual Shoes', 'desc':'girls, women',},
							{'name':'Heels', 'desc':'girls, women',},
							{'name':'Sports Shoes & Floaters', 'desc':'girls, women',},
							{'name':'Sports & Active Wear', 'desc':'girls, women',},
						],
					},
					{'name':'Accessories', 'desc':'girls, women',
						'sub':[
							{'name':'Sports Equipment', 'desc':'girls, women',},
							{'name':'Handbags, Bags & Wallets', 'desc':'girls, women',},
							{'name':'Watches & Wearables', 'desc':'girls, women',},
							{'name':'Sunglasses & Frames', 'desc':'girls, women',},
							{'name':'Headphones & Earphones', 'desc':'girls, women',},
							{'name':'Luggage & Trolleys', 'desc':'girls, women',},
							{'name':'Cosmetics & Personal Care', 'desc':'girls, women',},
							{'name':'Fashion Accessories', 'desc':'girls, women',},
							{'name':'Belts', 'desc':'girls, women',},
							{'name':'Scarves, Stoles & Gloves', 'desc':'girls, women',},
							{'name':'Caps & Hats', 'desc':'girls, women',},
							{'name':'Hair Accessories', 'desc':'girls, women',},
							{'name':'Socks', 'desc':'girls, women',},
							{'name':'Hair Straightners', 'desc':'girls, women',},
							{'name':'Hair Dryers', 'desc':'girls, women',},
							{'name':'Beauty & Grooming', 'desc':'girls, women',},
							{'name':'Make Up', 'desc':'girls, women',},
							{'name':'Skin Care', 'desc':'girls, women',},
							{'name':'Deodorants & Perfumes', 'desc':'girls, women',},
						]
					},
					{'name':'Jewellery', 'desc':'girls, women',
						'sub':[
							{'name':'Precious Jewellery', 'desc':'girls, women',},
							{'name':'Artificial Jewellery', 'desc':'girls, women',},
							{'name':'Silver Jewellery', 'desc':'girls, women',},
							{'name':'Gold jewellery', 'desc':'girls, women',},
							{'name':'Precious Jewellery', 'desc':'girls, women',},
						],
					},
				],
			},
			{'name':'Books', 'desc':'',
				'sub':[
					{'name':'Entrance Exams', 'desc':'',},
					{'name':'Academic', 'desc':'',},
					{'name':'Novels', 'desc':'',},
					{'name':'History', 'desc':'',},
					{'name':'Science', 'desc':'',},
					{'name':'Literature & Fiction', 'desc':'',},
					{'name':'Indian Writing', 'desc':'',},
					{'name':'Biographies', 'desc':'',},
					{'name':'Children', 'desc':'',},
					{'name':'Business', 'desc':'',},
					{'name':'Self Help', 'desc':'',},
					{'name':'Comics', 'desc':'',},
					{'name':'Stationery', 'desc':'',},
					{'name':'Pens', 'desc':'',},
					{'name':'Diaries', 'desc':'',},
					{'name':'Key Chains', 'desc':'',},
					{'name':'Desk Organisers', 'desc':'',},
					{'name':'Guide books', 'desc':'',},
				],
			},
			{'name':'Accessories', 'desc':'',
				'sub':[
					{'name':'Car & Bike Accessories', 'desc':'',
						'desc':[
							{'name':'Car & Bike Accessories', 'desc':'',},
							{'name':'Car Body Cover', 'desc':'',},
							{'name':'Bike Body Cover', 'desc':'',},
							{'name':'Car Air Freshener', 'desc':'',},
							{'name':'Vehicle Washing & Cleaning', 'desc':'',},
							{'name':'Car Sun Shade', 'desc':'',},
							{'name':'Car Mat', 'desc':'',},
							{'name':'Car Electronics & Appliances', 'desc':'',},
							{'name':'Car Media Player', 'desc':'',},
							{'name':'Car Pressure Washer', 'desc':'',},
							{'name':'Car Charger', 'desc':'',},
							{'name':'Car Bluetooth Device', 'desc':'',},
							{'name':'Car Vacuum Cleaner', 'desc':'',},
							{'name':'Car Refrigerator', 'desc':'',},
							{'name':'Helmets & Riding Gear', 'desc':'',},
						],
					},
					{'name':'Sports Accessories', 'desc':'Football, cricket,',
						'sub':[
							{'name':'Football', 'desc':'',
								'sub':[
									{'name':'Footballs', 'desc':'',},
								],
							},
							{'name':'Cricket', 'desc':'',
								'sub':[
									{'name':'bats', 'desc':'',},
									{'name':'balls', 'desc':'',},
									{'name':'stumps', 'desc':'',},
								],
							},
						],
					},
				],
			},
		],
	},
]
'''
gCategories = [
	{'name':'All', 'desc': 'All the categories'},
	{'name':'New Stuff', 'desc':'New deals, latest trend, frequently accessed'},
	{'name':'Online Offers', 'desc':'Online stores offers, deals, descounts, coupons'},
	{'name':'Computers & Electronics', 'desc':'Computers, Laptops, tablets, Phones, Desktops, Computer Accessories'},
	{'name':'Fashion & Clothing', 'desc':'Men, Women, Kids, sports wear, causal wear'},
	{'name':'Home Accessories', 'desc':'Kichen, Home, living room , bed room utilities'},
	{'name':'Accessories', 'desc':'Dell, HP, Lenovo, IBM, Toshiba'},
	{'name':'General', 'desc':'Dell, HP, Lenovo, IBM, Toshiba'},
]
'''

gBrands = [
	'',
]
