# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('house_info', models.CharField(blank=True, max_length=50)),
                ('geo_long', models.CharField(blank=True, max_length=10)),
                ('geo_lat', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(blank=True, max_length=50)),
                ('area_pin', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('fk_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='fk_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.City'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State'),
        ),
        migrations.AddField(
            model_name='address',
            name='fk_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Area'),
        ),
    ]
