# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-12 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
    ]
